In [1]:
import numpy as np

a = np.array([2, 5, 6])
b = np.array([3, 7, 4])

crossProduct = np.cross(a, b)
print(crossProduct)

[-22  10  -1]


In [6]:
a = np.array([[2, 3, 1],
             [4, 0, 5]])
b = np.array([[1, 4],
             [2, 3],
             [0, 6]])

crossProduct = a @ b
print(crossProduct)

[[ 8 23]
 [ 4 46]]


In [7]:
A = np.array([[4, 1],
              [2, 3]])
eigvalues, _ = np.linalg.eig(A)
print(eigvalues)

[5. 2.]


In [8]:
v = np.array([3, 2])
T = np.array([[2, 0],
              [0, 0.5]])

result = v @ T
print(result)



[6. 1.]


In [9]:
from scipy.linalg import lu

A = np.array([[2, 1],
              [8, 7]])
P, L, U = lu(A)

print("P:\n", P)
print("L:\n", L)
print("U:\n", U)
# Verify that PA = LU
print("PA:\n", np.dot(P, A))
print("LU:\n", np.dot(L, U))


P:
 [[0. 1.]
 [1. 0.]]
L:
 [[1.   0.  ]
 [0.25 1.  ]]
U:
 [[ 8.    7.  ]
 [ 0.   -0.75]]
PA:
 [[8. 7.]
 [2. 1.]]
LU:
 [[8. 7.]
 [2. 1.]]


In [10]:
# Doolittle LU decomposition for a 2x2 matrix (no pivoting)
A = np.array([[2, 1],
              [8, 7]])

# Initialize L and U
L = np.zeros((2,2))
U = np.zeros((2,2))

# Doolittle algorithm
L[0,0] = 1
L[1,0] = A[1,0] / A[0,0]
L[1,1] = 1
U[0,0] = A[0,0]
U[0,1] = A[0,1]
U[1,1] = A[1,1] - L[1,0]*U[0,1]

print("L:\n", L)
print("U:\n", U)
# Verify that A = L @ U
print("L @ U:\n", L @ U)

L:
 [[1. 0.]
 [4. 1.]]
U:
 [[2. 1.]
 [0. 3.]]
L @ U:
 [[2. 1.]
 [8. 7.]]
