In [ ]:
# Import necessary libraries
import numpy as np

In [ ]:
# Vectors
# Let's define some vectors for our examples
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9, 10])


array([5, 7, 9])

In [ ]:
# Vector addition
a+b


In [ ]:
# Vector subtraction
a-b

array([-3, -3, -3])

In [ ]:
# Vector multiplication (element-wise)
a*b

array([ 4, 10, 18])

In [ ]:
# Vector division (element-wise)
b/a

array([4. , 2.5, 2. ])

In [ ]:
# Scalar multiplication on a vector
2*a

array([2, 4, 6])

In [ ]:
# Scalar multiplication on a vector (using list)
2*[1, 2, 3]

[1, 2, 3, 1, 2, 3]

In [35]:
# Dot product
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.dot(a, b)
np.dot(b, a)

print(np.dot(a, b))  # 1*4 + 2*5 + 3*6 = 4+10+18=32
print(np.dot(b, a))  # 4*1 + 5*2 + 6*3 = 4+10+18=32


32
32


In [36]:

c = np.array([7, 8, 9])

print(np.dot(a, b+c))

# Distributive property of dot product
np.dot(a, b+c) == np.dot(a, b) + np.dot(a, c)

82


np.True_

In [ ]:
from numpy import linalg as lng

# Magnitude/norm/length of vector  
# ||a|| = sqrt(a[0]^2 + a[1]^2 + a[2]^2)   

a = np.array([1, 2, 3])
lng.norm(a)

np.float64(3.7416573867739413)

In [ ]:
# Vector Projection in Linear Algebra

# A projection is the process of finding how much of one vector lies in the direction of another—like the "shadow" of one vector onto another.

# Core Idea:
# The projection of vector a onto vector b shows how much a aligns with b. Geometrically, it’s the shadow cast by a onto the line defined by b.

# Formula:
# For vectors a and b:
# Projection of a onto b = (a · b / |b|²) * b
# Where:
#   a · b is the dot product.
#   |b| is the magnitude (length) of b.

# The result is a vector in the same direction as b, with length equal to the component of a along b.

In [ ]:
import  numpy as np

a = np.array([2, 3])
b = np.array([1, 0])

# Compute projection of a on b
# Projection of a onto b = (a · b / |b|²) * b
projection_length = np.dot(a, b)/ np.dot(b, b)
projection_vector = projection_length * b

print(projection_vector)    # Output: [2.0]

In [39]:
# Vector projection

# Projecting b onto a
# proj_a(b) = (a . b / ||a||^2) * a i.e. projecting b onto a
projbona = (np.dot(a, b) / lng.norm(a)**2) * a
print(projbona)

#  Projecting a onto b
# proj_b(a) = (b . a / ||b||^2) * b i.e. projecting a onto b
projaonb = (np.dot(b, a) / lng.norm(b)**2) * b
print(projaonb)

[2.28571429 4.57142857 6.85714286]
[1.66233766 2.07792208 2.49350649]


In [49]:
# Changing basis of vectors

a = np.array([4, -3])

# Let's say we want to express vector a in terms of two new basis vectors f1 and f2.
# We can find the coefficients x1 and x2 such that a = x1 * f1 + x2 * f2.
f1 = np.array([2, 1])
f2 = np.array([-1, 2])

f1dot_f2 = np.dot(f1, f2)
print(f"Dot product of f1 and f2: {f1dot_f2}")  # This will print the dot product of f1 and f2
# Dot product of f1 and f2: 0 implies that f1 and f2 are orthogonal

# Expressing a in terms of f1 and f2
# a = x1 * f1 + x2 * f2 

# To find x1 and x2, we can use the following equations:
# x1 = (a . f1) / ||f1||^2
# x2 = (a . f2) / ||f2||^2
x1 = (np.dot(a, f1) / lng.norm(f1)**2)
x2 = (np.dot(a, f2) / lng.norm(f2)**2)

print(f"Coefficients x1 and x2: {x1}, {x2}")  # This will print the coefficients x1 and x2

# Now we can express a in terms of f1 and f2
a_in_f1_f2 = x1 * f1 + x2 * f2

# To change the basis of a vector, we can use the coefficients x1 and x2
# to express a in terms of the new basis vectors f1 and f2.
# This is useful in many applications, such as computer graphics and physics simulations.

print(f"Vector a expressed in terms of f1 and f2: {a_in_f1_f2}")    

Dot product of f1 and f2: 0
Coefficients x1 and x2: 0.9999999999999998, -1.9999999999999996
Vector a expressed in terms of f1 and f2: [ 4. -3.]


In [45]:
# Formula for projecting a onto f1 and f2:
# proj_f1(a) = (a . f1 / ||f1||^2) * f1
# proj_f2(a) = (a . f2 / ||f2||^2) * f2

# Projecting a onto f1 and f2
proj_a_f1 = (np.dot(a, f1) / lng.norm(f1)**2) * f1
proj_a_f2 = (np.dot(a, f2) / lng.norm(f2)**2) * f2

print(f"Projection of a onto f1: {proj_a_f1}")  # This will print the projection of a onto f1
print(f"Projection of a onto f2: {proj_a_f2}")  # This will print the projection of a onto f2

Projection of a onto f1: [2. 1.]
Projection of a onto f2: [ 2. -4.]
