In [ ]:
# A matrix in Python is a two-dimensional array (or list of lists) 
# used to organize numbers in rows and columns. 

# Matrices are rectangular arrays of numbers, symbols, or expressions, 
# arranged in rows and columns. They are used in various fields such as
# mathematics, physics, computer science, and engineering to represent
# and manipulate data, perform linear transformations, and solve systems
# of linear equations.

In [13]:
# Matrix Addition and Subtraction
# Matrices of the same size can be added or subtracted by adding/subtracting 
# their corresponding elements.

import numpy as np

# Define two matrices
A = np.array([
    [1, 2],
    [3, 4]
])
B = np.array([
    [5, 6],
    [7, 8]
])

addition = A + B    # Result: [[5, 7], [9, 11]]
subtraction = A - B # Result: [[-3, -3], [-3, -3]]

print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("A + B:\n", addition)
print("A - B:\n", subtraction)


Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
A + B:
 [[ 6  8]
 [10 12]]
A - B:
 [[-4 -4]
 [-4 -4]]


In [14]:
# Matrix multiplication (dot product)
# The dot product of two matrices is calculated by multiplying rows of the first matrix
# by columns of the second matrix and summing the results.
# Number of columns in first matrix must equal number of rows in second matrix

C = np.dot(A, B)
print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("A * B:\n", C)

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
A * B:
 [[19 22]
 [43 50]]


In [4]:
# Matrix Scalar Operations
# Multiply (or divide) every element of a matrix by a number (scalar)

A = np.array([[1, 2], [3, 4]])
scalar_mult = 3 * A    
scalar_div = A / 2

print("Matrix A:\n", A)
print("Scalar Multiplication (3 * A):\n", scalar_mult)
print("Scalar Division (A / 2):\n", scalar_div)

Matrix A:
 [[1 2]
 [3 4]]
Scalar Multiplication (3 * A):
 [[ 3  6]
 [ 9 12]]
Scalar Division (A / 2):
 [[0.5 1. ]
 [1.5 2. ]]


In [5]:
# Mirroring a Matrix

# Create a sample matrix
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Mirror the matrix horizontally (flip left-right)
A_mirrored = np.fliplr(A)

print("Original matrix:\n", A)
print("Mirrored matrix:\n", A_mirrored)

Original matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Mirrored matrix:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


In [6]:
# Transposing a Matrix
# Transposing a matrix involves swapping its rows with its columns.

S = np.array([
    [1, 2, 3],
    [2, 5, 6],
    [3, 6, 9]
])
print("Original matrix S:\n", S)
print("Transpose of S:\n", S.T)
print("Is symmetric? ", np.array_equal(S, S.T))  # True

Original matrix S:
 [[1 2 3]
 [2 5 6]
 [3 6 9]]
Transpose of S:
 [[1 2 3]
 [2 5 6]
 [3 6 9]]
Is symmetric?  True


In [7]:
# Identity Matrix
# An identity matrix is a square matrix with ones on the main diagonal
# and zeros elsewhere. It acts as the multiplicative identity in matrix multiplication.

# Create an identity matrix (3x3)
I = np.eye(3)
print("Identity matrix:\n", I)

Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Multiplying any matrix by the identity matrix returns the original matrix

I = np.eye(3)

# Create another matrix
B = np.array([
    [2, 0, 1],
    [1, 3, 4],
    [0, 5, 6]
])

# Multiply identity matrix by B
result = np.dot(I, B)

print("Matrix B:\n", B)
print("Identity matrix:\n", I)
print("I * B:\n", result)
print("Is I * B same as B?", np.array_equal(result, B))  #

Matrix B:
 [[2 0 1]
 [1 3 4]
 [0 5 6]]
Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
I * B:
 [[2. 0. 1.]
 [1. 3. 4.]
 [0. 5. 6.]]
Is I * B same as B? True


In [8]:
#  Other types of matrices include:
#  - Zero Matrix: All elements are zero.
#  - Diagonal Matrix: Only diagonal elements are non-zero.
#  - Symmetric Matrix: Equal to its transpose.
#  - Square Matrix: Same number of rows and columns.

#  Zero Matrix
zero = np.zeros((2, 2))
print("Zero Matrix:\n", zero)

Zero Matrix:
 [[0. 0.]
 [0. 0.]]


In [11]:
# Matrix Properties

# Associative:
# (A×B)×C = A×(B×C)

# Distributive:
# A×(B+C) = (A×B) + (A×C)

# Non-Commutative:
# A×B ≠ B×A in general

In [ ]:
# Sources:

# [1](https://www.programiz.com/python-programming/matrix)
# [2](https://rootstack.com/en/blog/matrix-python-basic-operations)
# [3](https://www.geeksforgeeks.org/python/python-matrix/)
# [4](https://www.tutorialspoint.com/python_data_structure/python_matrix.htm)
# [5](http://rlhick.people.wm.edu/stories/linear-algebra-python-basics.html)
# [6](https://www.geeksforgeeks.org/python/adding-and-subtracting-matrices-in-python/)
# [7](https://www.digitalocean.com/community/tutorials/numpy-matrix-multiplication)
# [8](https://python-course.eu/numerical-programming/matrix-arithmetics-under-numpy-and-python.php)
# [9](https://www.statology.org/how-to-perform-matrix-addition-and-subtraction-in-python/)
# [10](https://www.geeksforgeeks.org/numpy/multiplication-two-matrices-single-line-using-numpy-python/)
# [11](https://t-redactyl.github.io/blog/2020/06/working-with-matrices-addition-subtraction-and-multiplication.html)