In [7]:
import numpy as np

# Define two matrices
A = np.array([
    [1, 2],
    [3, 4]
])
B = np.array([
    [5, 6],
    [7, 8]
])

# Matrix multiplication (dot product)
C = np.dot(A, B)
print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("A * B:\n", C)

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
A * B:
 [[19 22]
 [43 50]]


In [ ]:
import numpy as np

# Create a sample matrix
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Mirror the matrix horizontally (flip left-right)
A_mirrored = np.fliplr(A)

print("Original matrix:\n", A)
print("Mirrored matrix:\n", A_mirrored)

Original matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Mirrored matrix:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


In [3]:
S = np.array([
    [1, 2, 3],
    [2, 5, 6],
    [3, 6, 9]
])
print("Original matrix S:\n", S)
print("Transpose of S:\n", S.T)
print("Is symmetric? ", np.array_equal(S, S.T))  # True

Original matrix S:
 [[1 2 3]
 [2 5 6]
 [3 6 9]]
Transpose of S:
 [[1 2 3]
 [2 5 6]
 [3 6 9]]
Is symmetric?  True


In [4]:
# Create an identity matrix (3x3)
I = np.eye(3)
print("Identity matrix:\n", I)

Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
# Create an identity matrix (3x3)
I = np.eye(3)

# Create another matrix
B = np.array([
    [2, 0, 1],
    [1, 3, 4],
    [0, 5, 6]
])

# Multiply identity matrix by B
result = np.dot(I, B)

print("Matrix B:\n", B)
print("Identity matrix:\n", I)
print("I * B:\n", result)
print("Is I * B same as B?", np.array_equal(result, B))  #

Matrix B:
 [[2 0 1]
 [1 3 4]
 [0 5 6]]
Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
I * B:
 [[2. 0. 1.]
 [1. 3. 4.]
 [0. 5. 6.]]
Is I * B same as B? True
