In [ ]:
# Matrix decomposition is the process of breaking a matrix into simpler, special 
# matrices that are easier to work with—helping in solving systems, inverting 
# matrices, or analyzing complex data. 
# 
# The two most common decompositions you encounter as a beginner are,
#   - LU Decomposition 
#   - Singular Value Decomposition (SVD)

# Just like factoring a number into primes, you can factor a matrix into 
# fundamental forms.

In [ ]:
# Why Decompose Matrices?

# - Solving Linear Systems: Decomposed matrices make it much more efficient and 
#   stable to solve equations of the form Ax = b.
# - Inverting Matrices: If you can decompose a matrix, finding its inverse gets 
#   easier.
# - Data Compression and Machine Learning: Data is compressed and patterns are 
#   extracted using techniques like SVD and PCA, which rely on matrix decomposition.

In [ ]:
# LU Decomposition (Lower-Upper Decomposition)

# LU decomposition writes a square matrix A as a product: 
#       A = LU, 
# or sometimes 
#       PA = LU 
# if row-swapping is needed (where P is a permutation matrix).

# L = Lower triangular: all entries above the diagonal are zero.
# U = Upper triangular: all entries below the diagonal are zero.

# How Does It Help?
# Solving Ax = b can be done in two easy triangular steps:
#   - Solve Ly = b for y via forward substitution.
#   - Solve Ux = y for x via back substitution.

# Useful for inverting matrices, finding determinants, and more.

In [1]:
import numpy as np
from scipy.linalg import lu

A = np.array([[2, 3, 1],
              [4, 7, 7],
              [6, 18, 22]])

P, L, U = lu(A)
print("P:\n", P)
print("L:\n", L)
print("U:\n", U)
# Verify that PA = LU
print("PA:\n", np.dot(P, A))
print("LU:\n", np.dot(L, U))

P:
 [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
L:
 [[1.         0.         0.        ]
 [0.66666667 1.         0.        ]
 [0.33333333 0.6        1.        ]]
U:
 [[ 6.         18.         22.        ]
 [ 0.         -5.         -7.66666667]
 [ 0.          0.         -1.73333333]]
PA:
 [[ 6. 18. 22.]
 [ 4.  7.  7.]
 [ 2.  3.  1.]]
LU:
 [[ 6. 18. 22.]
 [ 4.  7.  7.]
 [ 2.  3.  1.]]


In [3]:
# Singular Value Decomposition (SVD)

# SVD generalizes the concept to any matrix (not just square ones) and is central in statistics, 
# machine learning, and data science.

# A = UΣVᵀ, 
# where:
#       U = Orthogonal matrix (columns called left singular vectors)
#       Σ = Diagonal matrix with non-negative numbers (singular values)
#       Vᵀ = Transpose of an orthogonal matrix (columns are right singular vectors)

# What Does SVD Do?
#   - It lets you break a matrix down into a set of axes and scales.
#   - Used to compress images, recommend Netflix shows, reduce noise from data, find patterns  
#       and more.
#   - You can even reconstruct A using only the largest few singular values for compact storage.



In [ ]:
import numpy as np
from scipy.linalg import svd

A = np.array([[1, 2, 3],
              [4, 5, 6]])

U, S, VT = svd(A, full_matrices=False)
print("U:\n", U)
print("Singular values:", S)
print("VT:\n", VT)

# Reconstruct A:
A_reconstructed = U @ np.diag(S) @ VT
print("A_reconstructed:\n", A_reconstructed)

# U and Vᵀ are like rotations of the axes.
# Σ squishes or stretches them. Usually, one or two singular values dominate—meaning your data 
# is actually lower rank and can be compressed efficiently.

U:
 [[-0.3863177   0.92236578]
 [-0.92236578 -0.3863177 ]]
Singular values: [9.508032   0.77286964]
VT:
 [[-0.42866713 -0.56630692 -0.7039467 ]
 [-0.80596391 -0.11238241  0.58119908]]
A_reconstructed:
 [[1. 2. 3.]
 [4. 5. 6.]]


In [ ]:
# Sources:
# [1](https://calcworkshop.com/matrix-algebra/matrix-factorization/)
# [2](https://www.machinelearningmastery.com/introduction-to-matrix-decompositions-for-machine-learning/)
# [3](https://www.youtube.com/watch?v=hZy-_PPQQao)
# [4](https://people.duke.edu/~ccc14/sta-663/LinearAlgebraMatrixDecompWithSolutions.html)
# [5](https://yaydede.github.io/toolbox/matrix-decompositions.html)
# [6](https://math.libretexts.org/Bookshelves/Combinatorics_and_Discrete_Mathematics/Applied_Discrete_Structures_(Doerr_and_Levasseur)/05:_Introduction_to_Matrix_Algebra/5.03:_Laws_of_Matrix_Algebra)
# [7](https://codesignal.com/learn/courses/linear-algebra-with-scipy/lessons/matrix-decomposition-with-scipy)
# [8](https://app.sophia.org/tutorials/matrix-decomposition)