In [4]:
# Matrix Inverse

# What is a Matrix Inverse?
# A matrix can be thought of as a function that transforms a vector.
# Example: A·X = B, where A is the transformation.
# To undo the transformation and recover X from B, use the inverse A⁻¹: X = A⁻¹·B.
# Multiplying by the inverse is like dividing by a number, but for matrices.
# Only square matrices (n×n) can have inverses.
# Non-singular matrices (determinant ≠ 0) have inverses.
# Singular matrices (determinant = 0) do not have inverses.

# Properties of Inverse Matrices
# For any invertible matrix A and the identity matrix I:
# A·A⁻¹ = I
# A⁻¹·A = I
# (A⁻¹)⁻¹ = A
# (AB)⁻¹ = B⁻¹A⁻¹
# (Aᵀ)⁻¹ = (A⁻¹)ᵀ
# The identity matrix I acts like 1 in arithmetic.

# How to Compute the Inverse Using Gaussian Elimination

# Example Matrix
# A =
# [ 2 1 -1 ]
# [ -3 -1 2 ]
# [ -2 1 2 ]

# Step 1: Form the Augmented Matrix
# Augment A with the identity matrix I:

# [ A | I ] =
# [ 2 1 -1 | 1 0 0 ]
# [ -3 -1 2 | 0 1 0 ]
# [ -2 1 2 | 0 0 1 ]

# Left side: matrix A
# Right side: identity matrix I
# Goal: Transform the left side into I using Gaussian elimination.

# Step 2: Apply Gaussian Elimination
# Forward elimination: eliminate below-diagonal entries.
# Backward elimination: eliminate above-diagonal entries.
# Scale rows so diagonal entries = 1.

# At the end:
# [ I | A⁻¹ ]

# The right side becomes the inverse matrix A⁻¹.
# Each column of A⁻¹ corresponds to the solution of AX = eᵢ, where eᵢ is the ith column of I.

# Step 3: Solve Linear Systems Using Inverse
# Once you have A⁻¹: X = A⁻¹·B.
# This solution is equivalent to solving AX = B directly using Gaussian elimination.
# However, explicitly computing the inverse is usually not needed.

In [5]:
import numpy as np

A = np.array([[2, 1, -1],
              [-3, -1, 2],
              [-2, 1, 2]], dtype=float)
A_inv = np.linalg.inv(A)
print("Original Matrix A:\n", A)
print("Inverse of Matrix A:\n", A_inv)

# The inverse of a matrix A is denoted as A^(-1) and satisfies the equation A * A^(-1) = I, where I is the identity matrix.

# The inverse of a matrix is a fundamental concept in linear algebra with applications in various fields, including machine learning, computer graphics, and physics.
# It is used to solve systems of linear equations, perform transformations, and analyze data.
# In this guide, we will explore the concept of the inverse of a matrix, how to compute it, and its applications.
# We will also discuss the conditions under which a matrix has an inverse and how to handle cases where the inverse does not exist.


Original Matrix A:
 [[ 2.  1. -1.]
 [-3. -1.  2.]
 [-2.  1.  2.]]
Inverse of Matrix A:
 [[ 4.  3. -1.]
 [-2. -2.  1.]
 [ 5.  4. -1.]]


In [6]:
I = np.dot(A, A_inv)
print("Product of A and A_inv (should be identity matrix):\n", I)   \
# Verify that A * A_inv = I
# Note: Not all matrices have an inverse. A matrix must be square (same number of rows and columns) and have a non-zero determinant to have an inverse.

Product of A and A_inv (should be identity matrix):
 [[ 1.00000000e+00  8.88178420e-16  0.00000000e+00]
 [ 1.77635684e-15  1.00000000e+00 -4.44089210e-16]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [8]:
# Determinant of a Matrix
# The determinant is a scalar value that can be computed from the elements of a square matrix.
# It provides important information about the matrix, such as whether it is invertible.
#   - If the determinant of a matrix is zero, the matrix is singular and does not have an inverse.
#   - If the determinant is non-zero, the matrix is non-singular and has an inverse

# Formula:  det(A) = ad - bc for a 2x2 matrix [[a, b], [c, d]]
# For larger matrices, the determinant can be computed using various methods, including row 
# reduction or cofactor expansion.

# For a 3x3 matrix, the determinant can be calculated as follows:
# det(A) = a(ei - fh) - b(di - fg) + c(dh - eg)
# where the matrix is:
# [[a, b, c],
#  [d, e, f],
#  [g, h, i]]

det_A = np.linalg.det(A)
print("Determinant of A:", det_A)
if det_A != 0:
    print("Matrix A has an inverse.")
else:
    print("Matrix A does not have an inverse.")

Determinant of A: -0.9999999999999996
Matrix A has an inverse.


In [ ]:
# Solve Ax = b using the inverse of A
# Concept: If A is invertible, the solution to the equation Ax = b can be found using,
# x = A^(-1)b.
# This method is particularly useful in various applications, including machine learning algorithms like linear regression.
b = np.array([8, -11, -3], dtype=float)
x = np.dot(A_inv, b)
print("Solution using A_inv * b:", x)