In [ ]:
# Orthonormal and Orthogonal Vectors

# Orthonormal vectors are both at right angles to each other (orthogonal: dot product = 0) and have a length of 1 (unit norm).

# For example, e1 = (1, 0) and e2 = (0, 1) are orthonormal.

In [1]:
import numpy as np  

e1 = np.array([1, 0])
e2 = np.array([0, 1])

# Check orthogonality
dot_product = np.dot(e1, e2)
print("Dot product (should be 0):", dot_product)

# Check unit norm
norm_e1 = np.linalg.norm(e1)
norm_e2 = np.linalg.norm(e2)
print("Norm of e1 (should be 1):", norm_e1)
print("Norm of e2 (should be 1):", norm_e2)

Dot product (should be 0): 0
Norm of e1 (should be 1): 1.0
Norm of e2 (should be 1): 1.0


In [3]:
# Orthogonal Matrix

# An orthogonal matrix (usually denoted Q) has rows and columns made up of orthonormal vectors.

# For a 2×2 case:
# Q = [[1, 0],
#      [0, 1]]

# This is orthogonal—the identity matrix.
Q = np.array([[1, 0], [0, 1]])

In [ ]:
# Matrix Transpose

# The transpose of a matrix flips its rows and columns.
A = np.array([[1, 2], [3, 4]])
A_T = np.transpose(A)

print("Original Matrix A:\n", A)
print("\nTransposed Matrix A_T:\n", A_T)

# or using .T
print(A.T)  

# "Diagonal elements stay the same" means values like A[0,0] and A[1,1] don’t move when transposing.

Original Matrix A:
 [[1 2]
 [3 4]]

Transposed Matrix A_T:
 [[1 3]
 [2 4]]
[[1 3]
 [2 4]]


In [ ]:
# Key Property of Orthogonal Matrices

# For an orthogonal matrix Q:
# Qᵀ Q = Q Qᵀ = I

# Multiplying its transpose by itself yields the identity matrix (1s on the diagonal, 0s elsewhere).

Q = np.array([[1, 0], [0, 1]])
Q_T = np.transpose(Q)
identity = np.dot(Q_T, Q)
print("Q^T * Q:\n", identity)

# For orthogonal matrices, the transpose is the same as the inverse:
# Qᵀ = Q⁻¹

Q_inv = np.linalg.inv(Q)
print("Q^T:\n", Q_T)
print("Q^-1:\n", Q_inv)
print("Q^T equals Q^-1:", np.array_equal(Q_T, Q_inv))


# This is not usually true for a random matrix.

Q^T * Q:
 [[1 0]
 [0 1]]
Q^T:
 [[1 0]
 [0 1]]
Q^-1:
 [[1. 0.]
 [0. 1.]]
Q^T equals Q^-1: True


In [ ]:
# Sources:
# [1](https://stackoverflow.com/questions/38426349/how-to-create-random-orthonormal-matrix-in-python-numpy)
# [2](https://datascienceparichay.com/article/numpy-check-if-a-matrix-is-orthogonal/)
# [3](https://www.geeksforgeeks.org/dsa/check-whether-given-matrix-orthogonal-not/)
# [4](https://github.com/xbeat/Machine-Learning/blob/main/Orthogonal%20Vectors%20in%20Python.md)
# [5](https://bvanderlei.github.io/jupyter-guide-to-linear-algebra/Orthogonalization.html)
# [6](https://www.learndatasci.com/glossary/orthogonal-and-orthonormal-vectors/)
# [7](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ortho_group.html)
# [8](https://www.thesecuritybuddy.com/linear-algebra/how-to-check-whether-a-matrix-is-an-orthogonal-matrix/)
# [9](https://www.machinelearningplus.com/linear-algebra/orthogonal-matrix/)