In [2]:
# Gram–Schmidt Process

# The Gram–Schmidt process is a systematic way of turning any set of basis vectors into an orthogonal (right-angle) basis, and then into an orthonormal basis (right-angle, unit-length)—using basic Python tools.

# What Is Gram–Schmidt?
# Takes a set of linearly independent vectors (basis) and transforms them so:
#   All vectors are at right angles (orthogonal) to each other.
#   Then they're scaled so each has length 1 (orthonormal).

# Orthogonal bases make calculations like projections, decompositions, and transformations much easier.


In [1]:
import numpy as np

# Step-by-Step Gram–Schmidt Process

# Suppose you have 3 basis vectors for ℝ³:
# u1, u2, u3
u1 = np.array([1, 1, 1])
u2 = np.array([1, 2, 2])
u3 = np.array([1, 1, 0])

# We want to find an orthogonal basis (v1, v2, v3) and then normalize to get an orthonormal basis.

# Step 1: First Vector
# Keep the first vector as it is:
v1 = u1

# Step 2: Orthogonalize Second Vector
# Remove the part of u2 that’s parallel to v1:
# v2 = u2 − proj_v1(u2)

# Where the projection formula is:
# projection of u2 onto v1:
# proj_v1(u2) = (u2 · v1 / ||v1||²) * v1
proj_u2_v1 = np.dot(u2, v1) / np.dot(v1, v1) * v1
v2 = u2 - proj_u2_v1

# Orthogonalize Third Vector
# Remove the part of u3 that’s parallel to both v1 and v2:
# v3 = u3 − proj_v1(u3) − proj_v2(u3)
proj_u3_v1 = np.dot(u3, v1) / np.dot(v1, v1) * v1
proj_u3_v2 = np.dot(u3, v2) / np.dot(v2, v2) * v2
v3 = u3 - proj_u3_v1 - proj_u3_v2

# Normalize
# Scale each orthogonal vector to have length 1:
# ei = vi / ||vi||
# Normalize each
e1 = v1 / np.linalg.norm(v1)
e2 = v2 / np.linalg.norm(v2)
e3 = v3 / np.linalg.norm(v3)

print("Orthonormal basis vectors:")
print(e1)
print(e2)
print(e3)

# This gives you 3 orthonormal vectors spanning the same space as the original ones.

# Key Points
# The first column stays the same; each next column is adjusted to be orthogonal to all previous ones.
# If you skip normalization, columns are orthogonal, but not unit length. Normalize for orthonormality.
# Python’s np.dot() computes dot products, and np.linalg.norm() computes lengths.

Orthonormal basis vectors:
[0.57735027 0.57735027 0.57735027]
[-0.81649658  0.40824829  0.40824829]
[-2.35513869e-16  7.07106781e-01 -7.07106781e-01]


In [ ]:
# Sources:
    
# [1](https://www.youtube.com/watch?v=zHbfZWZJTGc)
# [2](https://math.hmc.edu/calculus/hmc-mathematics-calculus-online-tutorials/linear-algebra/gram-schmidt-method/)
# [3](https://www.khanacademy.org/math/linear-algebra/alternate-bases/orthonormal-basis/v/linear-algebra-the-gram-schmidt-process)
# [4](https://calcworkshop.com/orthogonality/the-gram-schmidt-process-and-qr-factorization/)
# [5](https://www.statlect.com/matrix-algebra/Gram-Schmidt-process)
# [6](https://math.libretexts.org/Bookshelves/Linear_Algebra/Book:_Linear_Algebra_(Schilling_Nachtergaele_and_Lankham)/09:_Inner_product_spaces/9.05:_The_Gram-Schmidt_Orthogonalization_procedure)
# [7](https://ocw.mit.edu/courses/18-06sc-linear-algebra-fall-2011/7ac32be444c25e48590f47573833ccc6_MIT18_06SCF11_Ses2.4sum.pdf)
# [8](https://www.youtube.com/watch?v=enWNFOfudYw)
# [9](https://www.youtube.com/watch?v=zti01DiImiQ)
# [10](https://www.khanacademy.org/math/linear-algebra/alternate-bases/orthonormal-basis/v/linear-algebra-gram-schmidt-process-example)