In [ ]:
# Why Change to the Eigenbasis?

# When multiplying a matrix by itself many times (raising to a power), direct calculation becomes slow and complex.

# Diagonalization makes these calculations easy—especially for large powers (e.g., T¹⁰⁰⁰).

# In the eigenbasis, the matrix acts simply:
# each basis vector just gets stretched by its eigenvalue.

In [ ]:
# Why This Matters for Powers

# To compute Tⁿ efficiently:

# Diagonalize:
# T = C D C⁻¹

# Raise to power:
# Tⁿ = C Dⁿ C⁻¹

# Where Dⁿ means simply raising each diagonal entry (the eigenvalues) to the power n.

In [4]:
# Step-by-Step: Diagonalizing a Matrix
# Suppose we have a square matrix T.

# Step 1: Find Eigenvalues and Eigenvectors

import numpy as np
T = np.array([[3, 1], [0, 2]])
eigenvalues, eigenvectors = np.linalg.eig(T)

print("Eigenvalues:", eigenvalues)      
print("Eigenvectors:\n", eigenvectors)

# eigenvalues: These go on the diagonal of the new matrix.
# eigenvectors: These become columns of the change-of-basis matrix.

Eigenvalues: [3. 2.]
Eigenvectors:
 [[ 1.         -0.70710678]
 [ 0.          0.70710678]]


In [6]:

# Step 2: Build the Eigenbasis Conversion Matrix
# Let C = matrix whose columns are the eigenvectors.
# Let D = diagonal matrix with eigenvalues on the diagonal.

C = eigenvectors
D = np.diag(eigenvalues)
C_inv = np.linalg.inv(C)

print("C:\n", C)
print("D:\n", D)
print("Cinv:\n", C_inv)

C:
 [[ 1.         -0.70710678]
 [ 0.          0.70710678]]
D:
 [[3. 0.]
 [0. 2.]]
Cinv:
 [[1.         1.        ]
 [0.         1.41421356]]


In [ ]:
# Step 3: Diagonalize
#  Diagonalization Formula: T = C D C⁻¹
T_reconstructed = C @ D @ C_inv
# @ means matrix multiplication.
print("T diagonalized:\n", T_reconstructed)

# Raise to power:
# Tⁿ = C Dⁿ C⁻¹

# For n = 5
D_n = np.diag(eigenvalues ** 5)
print("Dⁿ:\n", D_n)

T_n = C @ D_n @ C_inv
print("Tⁿ:\n", T_n)


T diagonalized:
 [[3. 1.]
 [0. 2.]]
Dⁿ:
 [[243.   0.]
 [  0.  32.]]
Tⁿ:
 [[243. 211.]
 [  0.  32.]]
